package com.utmaximur.remote.errors

sealed class NetworkError : Throwable()